INCOME_TAX_RATE = 0.10
BUSINESS_TAX_RATE = 0.17
HOUSE_RATE = 0.02
FIRM_THRESHOLD = 20
HOUSE_PRICE_TO_INCOME = 15.0  # house price/ mean income ration (useless)
WEALTH_TO_INCOME = 1.2 # (useless)
BUY_HOUSE_BOUND = 30000  # the maxium asset people entry
DISTANCE_TRIGGER_TO_CHANGE_JOB = 10000
THRESHOLD_TO_CREATE_FIRM = 20 # create company after n iteration
THRESHOLD_TO_ADD_PERSON = 20 # born new citizen after n iteration
MAX_DAYS = 2920